### ISSUE TITLE
It opens with himself

### ISSUE THREAD

**Issue by sizarazad86** [valnub/Framework7-Plugin-Welcomescreen#14]
Hello, I did every thing & every thing is ok, but
when i refresh the page it opens with himself
i want to disable that, could you tell me how?

thx

**Comment by valnub** [comment]
What?

**Comment by sizarazad86** [comment]
when i refresh the homepage the welcome screen pops up directly and every time,
i don`t want it to do that
i want it to open when i click a spesific button can you help me with that?

**Comment by valnub** [comment]
Please read the docs. They clearly state that you need to set open:false in options:

```javascript
var myapp = new Framework7();
var options = {
  open:false
}
var welcomescreen = myapp.welcomescreen(welcomescreen_slides, options);
```

Cite:
> open (Default: true) Open welcome screen on init

**Comment by sizarazad86** [comment]
i did add the "open: false" but still opens once i refresh the page :(

**Comment by valnub** [comment]
I just tried the open option within the provided example and it works for me. Can you provide your code in a fiddle or codepen so I can look into it?

- http://www.codepen.io
- http://www.jsfiddle.net

**Comment by sizarazad86** [comment]
Thx so much i fixed it.
Can you help me with some framework7 addons?
