### ISSUE TITLE
How to show welcome screen only one time after the app is installed.

### ISSUE THREAD

**Issue by johanan7** [valnub/Framework7-Plugin-Welcomescreen#18]
Hello Welcome screen team, Greetings.  Is there any way to show welcome screen only the first time after the app is installed. when the user opens the second time, i dont wanna show welcome screen.

**Comment by tinyCoder32** [comment]
Hi, that's easy:

```
var welcomeTour = localStorage.getItem("tour");
if (!tour || tour == "0") {
	var welcomeText = [{
		id: 'slide0',
		picture: '<img src="image0.svg">',
		text: 'First slide'
	}, {
		id: 'slide1',
		picture: '<img src="image1.svg">',
		text: 'Second slide'
	}, {
		id: 'slide2',
		picture: '<img src="image2.svg">',
		text: 'Third slide'
	}];
	myApp.welcomescreen(welcomeText, {
		'bgcolor': '#f7f7f8',
		'fontcolor': '#007aff',
		'closeButtonText': 'SKIP',
		'onClosed': function() {
      		      	localStorage.setItem("tour", "1"); // will not make the tour run again
          	}
	});
}
```

Good luck.

**Comment by johanan7** [comment]
Hello @tinyCoder32  thanks for writing back.  I am new to javascript. can you show any working examples using codepen or anything. thanks in advance.

**Comment by tinyCoder32** [comment]
Use the basic example:
https://github.com/valnub/Framework7-Plugin-Welcomescreen/blob/master/example/js/myapp/pages/IndexPageController.js

Replace the code from line `12` to `44` with the code I pasted above.

**Comment by johanan7** [comment]
hello @tinyCoder32  i tried you code. and set local storage 
`localStorage.setItem("tour", "0");`
but its not working. in console i get error saying 'uncaught referenceError: tour is not defined'

**Comment by tinyCoder32** [comment]
Are you using jQuery with Framework7 ?!

This kind of errors happen when you use `localStorage` inside `$(document).ready(function () {`, you should keep it outside:

```
var welcomeTour = localStorage.getItem("tour");
$(document).ready(function () {
// rest of the code
});
```

**Comment by johanan7** [comment]
no i am not using jquery. 
I am using same basic example.

its showing error on line 14

**Comment by tinyCoder32** [comment]
Hold on a second, I am creating a jsfiddle demo for you.

**Comment by johanan7** [comment]
Just curious. Is jsfiddle demo ready

**Comment by tinyCoder32** [comment]
Not sure why I couldn't setup the plugin in a jsfiddle demo! maybe we need to ask @valnub about it, I got errors there that `welcomescreen is not a function`, but on my local script it is fine.

Please try putting `var welcomeTour = localStorage.getItem("tour");` at the top of your script file.

**Comment by johanan7** [comment]
already tried. if its working for you on local script. share it on jsfiddle. i will try adding plugin files on my local script. 
Or else can we try https://github.com/valnub/welcomescreen.js that does not rely on f7

**Comment by valnub** [comment]
@tinyCoder32 is right, localStorage should be the way to go.

@johanan7 There is most likely an error in your code if it doesn't work for you. Can you show it to us?

**Comment by valnub** [comment]
Closed due to no further response

**Comment by arnoldmukisa** [comment]
@valnub I have the same issue,
in the console, I get  'uncaught reference error: tour is not defined'
