### ISSUE TITLE
'open':'false' block the use of welcome screen

### ISSUE THREAD

**Issue by cedhuf** [valnub/Framework7-Plugin-Welcomescreen#2]
Hi,
When we use the `'open':'false'` option (to block the automatic beginning of the welcome screen), we can't start the slider with a simple `<a href="#" class="tutorial-open-btn button">Open Welcome Screen</a>`.

Is there any solution to be able to launch the welcome screen only on demand and not after every refresh ?

Thanks. Br,

**Comment by valnub** [comment]
Hi,
check out the example code. You can use:

welcomescreen.open();

welcomescreen.close();

**Comment by cedhuf** [comment]
Thanks. It turns out i wasn't editing the right file !! Sorry for the inconvenience.

By the way, nice plugin. Thanks again.
Br,

**Comment by valnub** [comment]
ha ha, yeah shit happens, no problem :-)
thanks mate
