### ISSUE TITLE
pagination not work in new version

### ISSUE THREAD

**Issue by kkordinia** [valnub/Framework7-Plugin-Welcomescreen#20]
in new version, after add title property for slide, pagination not work. please check example in [your files](https://github.com/valnub/Framework7-Plugin-Welcomescreen/tree/master/example).

**Comment by valnub** [comment]
@razekteixeira Could this be related to your last PR? I didn't do any changes since then. Could you look into this please? Thanks

**Comment by valnub** [comment]
@razekteixeira Would you please fix this issue until Friday, otherwise I'd have to revert your PR.

**Comment by valnub** [comment]
@kkordinia Should be fixed now. Let us now if it works, thanks! :-)
