### ISSUE TITLE
appened welcomescreen container to page element

### ISSUE THREAD

**Issue by kkordinia** [valnub/Framework7-Plugin-Welcomescreen#23]
I think it is better that welcomescreen container appened to page element (class="page").

**Comment by valnub** [comment]
Why do you think that?

**Comment by razekteixeira** [comment]
IMHO it doesn't make sense to be appended to the page element ;)

**Comment by kkordinia** [comment]
in some apps when user not registered welcomescreen opened. There is a link to login page. when user click and go ro login page welcomescreen is open. developer should a could for close or hide welcomescreen but when user press backbutton in android and back to home page welcomescreen not display.

**Comment by razekteixeira** [comment]
Sorry @kkordinia but to be honest I didn't get it :S lol
