### ISSUE TITLE
template for welcomescreen

### ISSUE THREAD

**Issue by kkordinia** [valnub/Framework7-Plugin-Welcomescreen#24]
please add template property in options to change template of welcomescreen with template7.

**Comment by valnub** [comment]
PR welcome :-)

**Comment by razekteixeira** [comment]
I'll take a look today and make the PR ok?

**Comment by valnub** [comment]
@razekteixeira Sure, if you want :-)

**Comment by valnub** [comment]
I just noticed that there is already a template option which can be set, it just wasn't in the documentation :D

@kkordinia Just set `options.template = yourTemplate;` and then pass options into Welcomescreen.
