### ISSUE TITLE
side panels issue

### ISSUE THREAD

**Issue by bigbossmaher** [valnub/Framework7-Plugin-Welcomescreen#27]
after installing the plugin , only the left side panel is oppened. even the right button is opening the left side panel

**Comment by valnub** [comment]
Can you provide a demo?

**Comment by bigbossmaher** [comment]
Please look to this video that i made 
https://youtu.be/ZoT304V6pEI

**Comment by valnub** [comment]
Can you provide a demo that reproduces the problem + your source code via [Gist](https://gist.github.com)?

**Comment by bigbossmaher** [comment]
a demo you mean the apk file ?

**Comment by bigbossmaher** [comment]
this is the gist 
https://gist.github.com/bigbossmaher/1a475544f664524738aa7187086cd8cf

**Comment by bigbossmaher** [comment]
i still waiting for your answer sir

**Comment by valnub** [comment]
I don't see deviceready event in your code. Aren't you using it?
You should wait for the event to trigger and then initialize your app.

**Comment by bigbossmaher** [comment]
hello , the device ready event is called in the index.html , the file that i sent to you contais the function that will be called in the index.html.
this is my index.html
https://gist.github.com/bigbossmaher/53ac7c8d9a1a6f025252f439a1d1ec63
( even i added the code in the device ready event i still get the same error )

**Comment by valnub** [comment]
Did you check console logs for JavaScript errors on startup?

**Comment by bigbossmaher** [comment]
i'm not getting any error

**Comment by valnub** [comment]
Very weird, I've never heard of anything like this. Can you post a web-based demo which only contains an absolute minimum of the code to reproduce the issue, for example using [Codepen](https://codepen.io) or [jsfiddle](http://jsfiddle.net) so we can look into the issue and debug?

**Comment by valnub** [comment]
Also, from where in index.html is your code from gistfile1.txt called?

I see lots of stuff in deviceready but nothing that points to code from gistfile1.txt.

Make sure to call the code from gistfile1.txt from within deviceready, not earlier.

**Comment by valnub** [comment]
You should also wait for DOMContentLoaded event.

So, it should be like this:

`Deviceready event -> DOMContentLoaded event -> Init F7 and Welcomescreen plugin`

None of your code should run before that.

**Comment by bigbossmaher** [comment]
if i send you all my cordova project can you please fix it , because i tried all you suggestions and the issue still happened

**Comment by valnub** [comment]
Sorry, I don’t have the time to fix other people’s projects.

I highly recommend to create minimal project to see if you can reproduce the problem. If yes, it might be an error in F7 or the plugin. If not, there is something wrong with your code.
