### ISSUE TITLE
Use in Framework7 v2

### ISSUE THREAD

**Issue by arifulalam** [valnub/Framework7-Plugin-Welcomescreen#28]
How to use this plugin for Framework7 v2?

And is it possible to automatically hide after 2/3 seconds?

Regards

**Comment by valnub** [comment]
Haven’t tried yet with v2. Gonna wait for the final release.

Sure, you can hide after few seconds by using setTimeout()

**Comment by valnub** [comment]
done! 😄 https://github.com/valnub/Framework7-Plugin-Welcomescreen/releases/tag/2.0b
