### ISSUE TITLE
white Screen on Tablette

### ISSUE THREAD

**Issue by bigbossmaher** [valnub/Framework7-Plugin-Welcomescreen#29]
i send the app to my friend that have a TAB E. he told me that he get a white screen howver it works on other devices . this is the aPK
besthost.tn/doc/android.apk

**Comment by valnub** [comment]
I don't have such a device. Can you debug into it with inspector and check what's going on?
If the page is entirely blank there is probably an issue with initialization.

**Comment by bigbossmaher** [comment]
initialization issue with Framework7 or Plugin-Welcomescreen ?

**Comment by valnub** [comment]
Could be one of them or even both.

Usually ppl run code before deviceready and DOMContentLoaded (aka ready event) are fired. Then js errors happen which lead to a blank screen on startup.

**Comment by bigbossmaher** [comment]
Thank you, is it important to use domcontentloaded ? Im using only document ready

**Comment by valnub** [comment]
Nah, it’s the same thing :)
