### ISSUE TITLE
The swiper.destroy(true) doesn't work

### ISSUE THREAD

**Issue by JoseWalker** [valnub/Framework7-Plugin-Welcomescreen#3]
Hi, 

With the latest version of Framework7 1.2.0, your nice plugin doesn't work, because if fails in the function that states:

self.close = function () {
      if (swiper) { swiper.destroy(true); }
      if (container) { container.remove(); }
      container = swiperContainer = swiper = undefined;
      if (typeof options.onClosed === 'function') { options.onClosed(); }
    };

it says:

TypeError: swiper.destroy is not a function. (In 'swiper.destroy(true)', 'swiper.destroy' is undefined)

in line 166 of welcomescreen.js.

Do you guys think there is a solution for this?! I would like to use the plugin in my app.

Regards,

Jose.

**Comment by valnub** [comment]
Hi, thanks for pointing out. I'll check what the problem is.

**Comment by valnub** [comment]
I checked on it and I cannot reproduce your error. However, there was a minor issue in the example because starting with F7 the .js lib files were renamed so the references had to be fixed. Please re-check your code or download the full zip and try the example.

**Comment by JoseWalker** [comment]
Thanks!!

I will check!!!

Regards

Enviado desde mi iPhone

**Comment by namdeveloper** [comment]
@JoseWalker may be, you call welcomescreen.open() after declare
 var welcomescreen = myApp.welcomescreen(welcomescreen_slides, options);
 //welcomescreen.open();

**Comment by JoseWalker** [comment]
That’s exactly what I did… I will download the full package again as Timo stated and see what happens… 

Thanks!

Jose F.C. Walker
CTO / SCA
Mov. +57 318 305 8430
Skype: jose.fernando.cardona.walker
LinkedIn: http://co.linkedin.com/in/riverst/

**Comment by JoseWalker** [comment]
I've tried with the latest version of F7  (1.3.0) and the new distribution from this git and nothing... same error:

TypeError: swiper.destroy is not a function. (In 'swiper.destroy(true)', 'swiper.destroy' is undefined)

**Comment by valnub** [comment]
Can you show me your code?
Just zip it and upload it here.

**Comment by JoseWalker** [comment]
Sure!

Here you go…

Regards,



Jose F.C. Walker
CTO / SCA
Mov. +57 318 305 8430
Skype: jose.fernando.cardona.walker
LinkedIn: http://co.linkedin.com/in/riverst/

**Comment by valnub** [comment]
Where is it? I don't see an attachment?

**Comment by JoseWalker** [comment]
Jess sorry… I did attach from my email client… how do I upload from the page? I’ve just tried and said that no ZIP allowed...


Jose F.C. Walker
CTO / SCA
Mov. +57 318 305 8430
Skype: jose.fernando.cardona.walker
LinkedIn: http://co.linkedin.com/in/riverst/

**Comment by valnub** [comment]
Oh, well. You got Dropbox?

**Comment by JoseWalker** [comment]
Thanks!!

Here you go… https://www.dropbox.com/s/k1parsdbhgq3nq4/www.zip?dl=0

Regards,

Jose F.C. Walker
CTO / SCA
Mov. +57 318 305 8430
Skype: jose.fernando.cardona.walker
LinkedIn: http://co.linkedin.com/in/riverst/

**Comment by valnub** [comment]
1. Don't call `welcomescreen.open()` unless you set `options.open = false` or you will call it twice which will result in an error.

2. Your script execution order looked a bit messed up, so I cleaned that up for you.

3. ***Never ever*** call script code before `deviceready` event was called in Cordova! In `IndexPageController` you initialized welcomescreen ***before*** `deviceready` was called. That's too early because DOM is not ready then, so I moved that code into `index.js` and run it after `deviceready` event has fired.

This should work: https://www.dropbox.com/s/zpd1yhloqx7gm9i/www.zip?dl=0

**Comment by JoseWalker** [comment]
Timo!

It worked! thank you very much for helping me on getting this sorted out… now I can use this welcome screen like a charm.

Regards,

Jose F.C. Walker
CTO / SCA
Mov. +57 318 305 8430
Skype: jose.fernando.cardona.walker
LinkedIn: http://co.linkedin.com/in/riverst/

**Comment by valnub** [comment]
You're welcome :)
