### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by robinyip** [valnub/Framework7-Plugin-Welcomescreen#32]
The pagination is not working and disappeared.

**Comment by valnub** [comment]
You're right! There was a bug which is fixed in latest release [2.1.1-beta](https://github.com/valnub/Framework7-Plugin-Welcomescreen/releases/tag/2.1.1-beta)
Please let me know if that fixes the issue for you.

**Comment by robinyip** [comment]
Thanks a lot, it works great.

The only thing is that the plugin name is changed from Framework7WelcomescreenPlugin to F7WelcomescreenPlugin so need some minor code modification but not a problem.
