### ISSUE TITLE
[v3.0] close event / swiper.destroy is not a function

### ISSUE THREAD

**Issue by vousys** [valnub/Framework7-Plugin-Welcomescreen#33]
Hi! I'm using this plugin with new f7 v3.
With the event:  
`app.welcomescreen.close();`
is throwing:

Uncaught TypeError: swiper.destroy is not a function
    at Welcomescreen.self.close (f7.welcomescreen.js:168) 

on this line
```

self.close = function () {
      if (swiper) { **swiper.destroy(true);** }
      if (container) { container.remove(); }
      container = swiperContainer = swiper = undefined;
      if (typeof options.onClosed === 'function') { options.onClosed(); }
    };
    
```

**Comment by valnub** [comment]
Hey, I tried the plugin with v3 and I cannot confirm this using the demo in this repo. There must be something wrong with your code. Based on the error message you get it looks like the `destroy()` function doesn't exist anymore in Swiper but looking into the source code of Swiper it still exists, so there must be something else wrong.
