### ISSUE TITLE
Welcomescreen Not Close on Android

### ISSUE THREAD

**Issue by Jimisfou** [valnub/Framework7-Plugin-Welcomescreen#34]
Hello,
I test the plugin in my PC and everything works fine,
but when I build the app and open it on android, 
the app.welcomescreen.close(); not working.

The skip button is working but when I press app.welcomescreen.close(); to close the welcome screen nothing happens.

I use the latest Framework7.

**Comment by valnub** [comment]
Hey, can you post the js error (if any) and some of your code? Thanks

**Comment by Jimisfou** [comment]
Hello @valnub ,
I have no js Error. 
My code is the above: 
`$$('#accountButton').click(function(){ app.welcomescreen.close();  });`
On click nothing happens.
I also manage to get it works. I open your library and in the init I put the above code:

```
      Dom7(document).on('click', '.accountButton', function (e) {
        e.preventDefault();
        var $wscreen = Dom7(this).parents('.welcomescreen-container');
        if ($wscreen.length > 0 && $wscreen[0].f7Welcomescreen) { $wscreen[0].f7Welcomescreen.close(); }
      });
```
But I think that this isn't the best solution.

Thank you

**Comment by valnub** [comment]
Hey, can you upload a working demo that replicates the problem somewhere so I can look into this? thanks
