### ISSUE TITLE
graceful exit *feature request*

### ISSUE THREAD

**Issue by prtnbs** [valnub/Framework7-Plugin-Welcomescreen#35]
would love the ability for the welcome screen to exit gracefully
also would love to be able to use css animations for each slide and use images for each slide: https://giphy.com/explore/onboarding

**Comment by valnub** [comment]
hey, thanks for your feedback. Can you explain a bit more in detail what you mean by "exit gracefully"?

If you want to add images easily through plain html in the "picture" attribute of each slide. The the Readme for more details.
