### ISSUE TITLE
F7/Phonegap/Vue: "Dom7 is undefined"

### ISSUE THREAD

**Issue by atnetws** [valnub/Framework7-Plugin-Welcomescreen#36]
Hi folks,
is this plugin suitable to be used in a F7/Phonegap/Vue template?
I used the Split View / Panel PhoneGap template from Framework7's templates download page and followed the instructions in the plugin's Readme.md, but as soon as I define
Framework7.use(welcomescreen);
I get "Dom7 is undefined" in the browsers error console. 

Steps to reproduce:
-Create project based on this template
https://github.com/phonegap/phonegap-template-vue-f7-split-panel
-NPM install the welcomescreen plugin, installed it as stated in the readme file

Am I missing something? Any hints appreciated!

**Comment by valnub** [comment]
Seems there is an incompatibility problem with Vue. Looking into this.

**Comment by valnub** [comment]
Fixed in version 2.1.4
Lemmi know if this works for you
