### ISSUE TITLE
Release to HTML5

### ISSUE THREAD

**Issue by snowbreeze** [valnub/Framework7-Plugin-Welcomescreen#4]
Hey,
Amazing plugin. But I cant wait to see this being available for any html site.
Sorry for opening as an issue, this is actually a feature request.

**Comment by valnub** [comment]
Hey, I didn't intend to release this as a more generic version but if enough ppl are interested in it, I'll sure take some time and release an non-F7-version.

**Comment by snowbreeze** [comment]
This would be really usefull. There's nothing simple for a welcome screen
at the moment.

**Comment by valnub** [comment]
I did a quick port, maybe this will work for you? https://github.com/valnub/welcomescreen-mobile
It's mostly untested, so let me know if you have any issues.

**Comment by snowbreeze** [comment]
Thanks a lot!!

**Comment by valnub** [comment]
You're welcome :)
