### ISSUE TITLE
Does not work or load at all

### ISSUE THREAD

**Issue by Izrab** [valnub/Framework7-Plugin-Welcomescreen#40]
I downloaded it and extracted f7.welcomescreen.js and f7.welcomescreen.css
I followed each step in the tutorial, but instead of using node js to package npm, I downloaded the latest release github repo as zip to use it local since it has zero dependency. But it didn’t work.
I import f7.welcomescreen.js and f7.welcomescreen.css like this in my index.html
<script type=“text/javascript” src=“lib/f7.welcomescreen.js”></script>
<link rel=“stylesheet” href=“lib/f7.welcomescreen.css”>
Even though this was not instructed in the tutorial.
In my main js file I tried all these

import welcomescreen from ‘lib/f7-welcomescreen.js’;

import welcomescreen from ‘lib/f7-welcomescreen’;

and similar typing but at the end it was no avail and didn’t work.
And of course, I have imported framework7.min.js and framework7.min.js initially.
I am stuck.

The weird thing is, if I import the bundle.js in my index.html it works, bundle.js is used in the demo example, but I believe it is an old version as indicated in the comments.

I want to use this library in my phonegap project but I move forward because of this problem.

**Comment by valnub** [comment]
Hi, two questions on this:

- Why don't you use npm to install the dependency?
- If using the bundle works why use the original files?

**Comment by Izrab** [comment]
Answers on the two questions

1. Because I don't know NPM well and I don't know where NPM stores the downloaded files so I can write their link directory in index html script tag. 
2. because the original and true libs of welcomescreen js and welcomescreen css and easily modifiable and readable and some other feelings.

How to use the originals without NPM or node js? welcomescreen does not have any dependencies listed in its npm webpage, so what is the usefulness of npm or node js in this case?

**Comment by valnub** [comment]
Izrab, if you don't know npm I highly recommend to learn it. It's an industry standard. The welcomescreen plugin has been built to be used via npm because it makes the library easy to import and to keep it up to date. Please understand that other methods are currently not supported. The bundle file you mentioned is very different from the src files because it contains a full demo. If you only want the library the src files should be sufficient. For me it sounds more like you did a mistake during the initialisation of welcomescreen. Can you post your code?

**Comment by Izrab** [comment]
I dragged the code in this reply.
[www.zip](https://github.com/valnub/Framework7-Plugin-Welcomescreen/files/2727672/www.zip)

**Comment by valnub** [comment]
I looked into your code and it's not possible to include an npm module like welcomescreen into your project. Also, you have the full F7 project as a folder in there which is wrong.

I ***highly*** recommend to start over from scratch using this template and NPM: https://github.com/phonegap/phonegap-template-vue-f7-blank

**Comment by valnub** [comment]
I highly recommend not to do so. The bundle does NOT only contain the library but it holds the full code for the DEMO.

**Comment by Izrab** [comment]
What is the difference between PG F7 starter template and my www folder (which was created with create blank project with PG desktop)?
Both contain index and css files and both include F7 lib folder (but mine is new version of F7)
And regarding the bundle demo, I was customizing the demo according to my own need...

**Comment by Izrab** [comment]
I don't understand NPM, where the downloaded content go? how they are imported the my-app.js? 
My style and way is to put all libraries and their dependencies in the warm www house, all local.

**Comment by valnub** [comment]
> What is the difference between PG F7 starter template and my www folder (which was created with create blank project with PG desktop)? Both contain index and css files and both include F7 lib folder (but mine is new version of F7)

You're right. phonegap-template-framework7 is as static as your www folder which is not good. There is no package management which means you have to maintain dependencies manually which is a big pain and you run in exactly the problems you're experiencing now. Instead better use [phonegap-template-vue-f7-blank](https://github.com/phonegap/phonegap-template-vue-f7-blank).

The template comes with module bundlers preconfigured so all your ES6 modules will automatically be converted to an ES5 bundle and new modules can easily be added using the `import` statement.

> I don't understand NPM, where the downloaded content go? how they are imported the my-app.js?
> My style and way is to put all libraries and their dependencies in the warm www house, all local.

It is **extremely** easy. All you have to do is run `npm install` first and it will install all your dependencies to a folder called `node_modules`. In your js or vue file you then simply import the stuff that your need.

**For example**, to add welcomescreen plugin just do `npm install f7-welcomescreen`. Then, in your js file or vue file add `import welcomescreen from 'f7-welcomescreen';` - Done! It's that easy.

To run the app in dev mode run `npm run dev`. To create the final production build run `npm run build-prod`. But this is all in the [readme of the template](https://github.com/phonegap/phonegap-template-vue-f7-blank). Please read it first.

Why not learn something new? If you keep doing this the "old style" you will be left behind quickly in the programming world.

**Comment by Izrab** [comment]
Thanks a lot.
