### ISSUE TITLE
Doesn't work with Framework7 v4.3.0

### ISSUE THREAD

**Issue by Utkarsh85** [valnub/Framework7-Plugin-Welcomescreen#42]
Presents error app.js:125 Uncaught TypeError: Cannot read property 'create' of undefined 
while doing 
```javascript
    function initSwiper() {
        swiper = window.swiper.create('.welcomescreen-swiper', {  <<<=====
            direction: 'horizontal',

```

**Comment by valnub** [comment]
Thanks for reporting! Will look into this

**Comment by valnub** [comment]
I think I figured out what’s wrong. Will post an update soon.

**Comment by valnub** [comment]
Turned out that you only have to use the bundle instead of regular F7 files: https://github.com/valnub/Framework7-Plugin-Welcomescreen/commit/49e3c515a268cbe478841f9511561d5ccef5ba57
