### ISSUE TITLE
not setting f7params.welcomescreen shows an empty screen

### ISSUE THREAD

**Issue by BananaAcid** [valnub/Framework7-Plugin-Welcomescreen#43]
I save to localStorage if the welcome screen has been shown before. If shown before, I do not set `f7params.welcomescreen` or to `f7params.welcomescreen = undefined`.

Both, as well as setting it to an empty object or object with empty slides, causes the welcomescreen to show a white sheet instead of not loading at all.

current workaround: option to add an additional class to hide the element (but it still sits in memory). Will try the onOpened to remove the dom node.

what I expect: not having it loaded.

**Comment by BananaAcid** [comment]
My suggested solution is
```
open: (localStorage.welcomescreen !== 'seen'), 
onClosed: e => { ocalStorage.welcomescreen = 'seen' },
```
...since the welcomescreen methods will still work - btw, close() will remove the DOM nodes, `open: false` will not add them.

maybe something to add to the readme.

**Comment by valnub** [comment]
Thanks
