### ISSUE TITLE
Using iOS fullscreen, leaves a gap

### ISSUE THREAD

**Issue by BananaAcid** [valnub/Framework7-Plugin-Welcomescreen#45]
using the header `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">` leaves a gap above the slides. (Careful when fixing: Even filling the gap, the top right link must stay at the same pos!)

It does not compensate for iOS fullscreen.

**Comment by valnub** [comment]
Cannot replicate issue. When using `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">` it works as expected in the [demo](https://github.com/valnub/Framework7-Plugin-Welcomescreen/tree/master/demo/dist) – no gap visible. I assume there is something else wrong with your project css.

<img width="200" src="https://user-images.githubusercontent.com/3787662/62512689-5322e600-b819-11e9-8975-67599048117f.PNG" alt="">

**Comment by BananaAcid** [comment]
Since the rest of the app works fine, I believe my issue is part of using Framework7.Vue with your plugin.
