### ISSUE TITLE
welcomescreen.js: Line 185 : Uncaught TypeError: swiper.destroy is not a function

### ISSUE THREAD

**Issue by ridiss1** [valnub/Framework7-Plugin-Welcomescreen#47]
Hi
I am using the welcome Screen F7 plugin to display a user guide but I get this error. 
My F7 Version is 1.4 (Very old)
I am using cordova/Android
Can Any one helps with that? Thanks.

09-29 08:10:02.734 19244-19244/com.idriss.karatou D/SystemWebChromeClient: file:///android_asset/www/js/welcomescreen.js: Line 185 : Uncaught TypeError: swiper.destroy is not a function
09-29 08:10:02.734 19244-19244/com.idriss.karatou I/chromium: [INFO:CONSOLE(185)] "Uncaught TypeError: swiper.destroy is not a function", source: file:///android_asset/www/js/welcomescreen.js (185)

**Comment by valnub** [comment]
Wow, that is really old :-)
Try the following:

1. Uninstall the plugin via `npm remove f7-welcomescreen`
2. Then check this old version of the plugin: https://github.com/valnub/Framework7-Plugin-Welcomescreen/tree/699c1015d48eebb56ddd026fe47e5d9909408cdc

Follow the instructions in the readme there. There is no npm install for this old version. You have to do that manually as the readme states. Good luck :-)

**Comment by ridiss1** [comment]
Thank you for your response. 

I have changed the plugin. I still have the same error at different line. 
The things that are not working are : Skip button, end of tuto and the navigation button.  I was thinking about using the swiper in an popup because now I can't close it.

**Comment by valnub** [comment]
Hm, I don't remember clearly but it's possible that old version of f7 didn't come with [Swiper.js](https://github.com/nolimits4web/swiper) preinstalled, so you can try to install that.

If that doesn't help, you can try other older versions of the plugin too:
- https://github.com/valnub/Framework7-Plugin-Welcomescreen/tree/1ec36ed4a4fe0819d7d6266c77bdda19c33c9c37
- https://github.com/valnub/welcomescreen.js

If you still have no luck you should seriously consider upgrading to latest F7 version..

**Comment by BananaAcid** [comment]
I got a similar error, after updating to the new version of Framework7. (might be the same)

Triggered when pressing the upper-right button to close the slides.

```
Uncaught TypeError: s.destroy is not a function
    at Welcomescreen.<anonymous> (VM15308 app.js:17)
    at HTMLDivElement.<anonymous> (VM15308 app.js:17)
    at HTMLDocument.o (VM15308 app.js:17)
(anonymous) @ app.js:17
(anonymous) @ VM15308 app.js:17
o @ VM15308 app.js:17
```

**Comment by valnub** [comment]
Can you post a *minimal* example project that reproduces the issue?

**Comment by BananaAcid** [comment]
I just added a foreach in the module, it works. But does not seem to trigger 'vue #app not found' error.

**Comment by valnub** [comment]
Is this still a problem or the ticket be closed?

**Comment by BananaAcid** [comment]
It is still a problem, but my workaround does it for me. Checking whether it is an array and using the slider elems of it, or using it as a  slider elem directly.
