### ISSUE TITLE
Hide view before welcome screen

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [valnub/Framework7-Plugin-Welcomescreen#6]
Hello Welcomescreem team,

Just before getting the welcome screen I see the framework view shortly. Is there a way to hide this?

Please advise.

Kind regards,
Mario

**Comment by valnub** [comment]
Hoi, Mario :)
Sorry for the late reply.

You need to do 2 things for faster loading:

1. Move all your F7 `<script>` references from `<body>` to `<head>`
2. Initialize your app and welcomescreen plugin **after** document is ready:

```javascript
  document.addEventListener("DOMContentLoaded", function(event) { 
    // Initialize app
    var fw7App = new Framework7(),
      fw7ViewOptions = {
        dynamicNavbar: true,
        domCache: true
      },
      mainView = fw7App.addView('.view-main', fw7ViewOptions),
      $$ = Dom7,
      ipc = new myapp.pages.IndexPageController(fw7App, $$);
  });
```

I did change the code in this repo so you can check out the faster result in the demo here: http://www.timo-ernst.net/misc/f7-plugin-welcomescreen/

Cheers!
Timo
