### ISSUE TITLE
Error when calling welcomescreen.open

### ISSUE THREAD

**Issue by macdonst** [valnub/Framework7-Plugin-Welcomescreen#8]
When I call welcomescreen.open() I get the following stack trace.

```
Uncaught TypeError: Cannot read property 'nodeType' of null(…)
window.Swiper @ framework7.js:13418
(anonymous function) @ framework7.js:13516
each @ framework7.js:11723
window.Swiper @ framework7.js:13515
initSwiper @ welcomescreen.js:60
Welcomescreen.self.open	@	welcomescreen.js:133
```

any ideas?

**Comment by valnub** [comment]
Can you show your code?

**Comment by macdonst** [comment]
@valnub sure, the code is up here on GitHub:

https://github.com/macdonst/FridayNightHockey/blob/master/www/js/my-app.js

**Comment by valnub** [comment]
Try to remove this line from your `deviceready` event listener:
`welcomescreen.open();`

`.open()` is called automatically when your site loads unless you set `open:false` in options

**Comment by macdonst** [comment]
@valnub FFS! Well I guess you can tell I was working on this late, late last night. Sorry to have wasted your time.

**Comment by valnub** [comment]
No prob, mate. Latenight programming is always the best! Happy coding :-)
